### ISSUE TITLE
ndkbulid problem

### ISSUE THREAD

**Issue by andyTsing** [linchaolong/ApkToolPlus#7]
Use NDKBULID generate SO library, packaged into JIAGU.ZIP, after installation, found that can not start, very strange

**Comment by linchaolong** [comment]
do you have to run `com.linchaolong.apktoolplus.builder.UpdateJiaGu` after ndk-build?

**Comment by andyTsing** [comment]
No, I configured ANT environment and found that ANDROID SDK environment lacks some configuration files for ANT, so can not compile successfully, but simply put the corresponding SO, and re-packaged into JIAGU.ZIP.
By the other hand, and then packaged the original SO file, really reinforcement process, Still feasible.

**Comment by linchaolong** [comment]
What can not start? ApkToolPlus or apk ? have any log?

**Comment by andyTsing** [comment]
UnsatisfiedLinkError No implementation found for byte[] com.linchaolong.apktoolplus.jiagu.utils.ApkToolPlus.decrypt(byte[])
TKS.
